### ISSUE TITLE
请教如何使用

### ISSUE THREAD

**Issue by tufu9441** [itsimba/typecho_to_hexo#1]
我想从typecho转入hexo，发现只有这么一个项目，但我比较小白，还不知道如何使用。我把整个文件夹下载到本地后，修改config.json中的信息为我现在VPS上typecho的数据库的信息，然后在本地终端中进入文件夹目录运行node mark.js，发现报错如下，于是我不知道该怎么正确的使用它了，是需要在服务器端操作吗？还请指教，非常感谢！
module.js:340
    throw err;
          ^
Error: Cannot find module 'to-markdown'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/whm/Downloads/typecho_to_hexo-master/mark.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by itsimba** [comment]
进入文件夹目录后，请使用 先输入 npm install 安装项目依赖！

**Comment by tufu9441** [comment]
我安装了项目依赖，然后运行node mark.js，还是报错……

**Comment by itsimba** [comment]
报什么错误？

**Comment by tufu9441** [comment]
@lauyoume  忘记了，不过现在我已经不用了，我已经通过其它方法转换过来了……

**Comment by bubbleatgit** [comment]
@tufu9441 请问你用什么方式转换的

**Comment by tufu9441** [comment]
@bubbleatgit hexo-migrator-rss
